# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-12 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'person type',
                'verbose_name_plural': 'person types',
                'db_table': 'person_general',
                'ordering': ('title',),
            },
        ),
    ]
