# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-19 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0003_auto_20180712_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True, verbose_name='gender'),
        ),
    ]
