# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-20 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0004_auto_20180719_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
        migrations.AddField(
            model_name='person',
            name='enrollment_no',
            field=models.IntegerField(default='160', unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sem',
            field=models.IntegerField(choices=[(1, '1'), (3, '3'), (5, '5'), (7, '7')], default='5'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
    ]
