# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-20 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0006_auto_20180720_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='enrollment_no',
        ),
    ]
