# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-20 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0007_remove_person_enrollment_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='enrollment_no',
            field=models.CharField(default='160', max_length=465, unique=True),
        ),
    ]
