# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-20 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0008_person_enrollment_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default='1999-08-28', verbose_name='birth date'),
        ),
    ]
