# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-21 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0011_auto_20180721_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='enrollment_no',
            field=models.CharField(default='160130107091', max_length=465),
        ),
    ]
