# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-24 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0016_auto_20180724_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='users',
        ),
    ]
