# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-24 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0018_auto_20180724_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_voted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='a',
            field=models.CharField(default='s', max_length=230),
        ),
    ]
