# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-24 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0019_auto_20180724_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='users',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
