# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-24 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human', '0020_auto_20180724_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('vada_paw', 'Vada Paw'), ('paw_bhaji', 'Paw Bhaji'), ('ghughra', 'Ghughra'), ('pani_puri', 'Pani Puri'), ('dal_pakwan', 'Dal Pakwan'), ('fruit_salad', 'Fruit Salad'), ('sandwhich', 'Sandwhich'), ('bhajiya', 'Bhajiya'), ('punjabi', 'Punjabi'), ('pizza', 'Pizza'), ('dabeli', 'Dabeli'), ('manchurian', 'Manchurian')], max_length=256, unique=True)),
                ('vote', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_voted', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
